### PR TITLE
Swift Package Manager support

### PR DESCRIPTION
**Pull request by ChrisChares**
Hi there!

Thanks for making SKQueue, really helped me out with some tooling I'm working on for a side project.

This PR adds support for the Swift Package Manager.  Unfortunately SPM requires Swift 3.0, so in order to do that I had to merge @rezozo's PR #3.  That PR is obviously still open with your concerns.  LMK how you want to proceed with this, I'd happily implement the changes you pointed out on his PR if that's what's needed.

Thanks!

### CODE REVIEW

**Comment by daniel-pedersen** [comment]
Thank you Chris! This looks awesome.

I was unfortunately forced to discard PR #3 since it was broken and I got no response on my review.

However, I just pushed Swift 3 support on master, so please transfer your commits in a branch off origin/master.

**Comment by Eitot** [comment]
Any update on this?

**Comment by daniel-pedersen** [comment]
I have added this now. See the README for more info.

**Comment by daniel-pedersen** [comment]
Forgot to add tag, fixed.

**Comment by daniel-pedersen** [comment]
I've recently brushed up on my git skills. Before I didn't know how to cherry-pick, fix conflicts and squash several commits at once (from another remote) - and still keep the same author. Now I know, so I have correctly credited @ChrisChares for everything provided in this PR 😄. Again, thank you!

**Pull request closed without merging**
